### ISSUE TITLE
.%02d is the appropriate way to express hundredths of seconds

### ISSUE THREAD

**Issue by duffy-corelight** [amzn/zeek-plugin-bacnet#16]
```
data[data_index] = fmt("time=%d:%02d:%02d.%d",
```
should be
```
data[data_index] = fmt("time=%d:%02d:%02d.%02d",
```
since `.%02d` not `.%d` is the appropriate way to express hundredths of seconds when the number might be less than two digits.

**Comment by NothinRandom** [comment]
@duffy-corelight, [latest update](https://github.com/amzn/zeek-plugin-bacnet/commit/4f91d6a9fd1ec24b2e10216cbbab8081774d4686#diff-e971e4317e8e746322cff8d24b0eff78R264) addresses this issue.  Like the others, I'll let the customer close the issue if deemed as satisfied.

**Comment by duffy-corelight** [comment]
Closed as corrected.
