### ISSUE TITLE
unsupported byte length for bytestring_to_count

### ISSUE THREAD

**Issue by voteblake** [amzn/zeek-plugin-bacnet#2]
Plugin is working, but when testing on internal PCAP's does emit an error for certain packets. This is not a critical error which prevents Zeek from continuing.

`1218932832.035836 error in /opt/bro/lib/zeek/plugins/packages/zeek-bacnet/scripts/./main.zeek, line 153: unsupported byte length for bytestring_to_count (bytestring_to_count(Bacnet::rest_of_data[(coerce Bacnet::rest_of_data_index to int), (coerce Bacnet::rest_of_data_index + Bacnet::len to int)], F))`

**Comment by voteblake** [comment]
Per https://github.com/zeek/zeek/blob/916205e254dad411bd22536acae0c6696cae9cbf/src/zeek.bif#L2654 argument `s` to `bytestring_to_count` must be size `uint8_t`, `uint16_t`, `uint32_t`, `uint64_t`. Currently it bails out and returns 0.

**Comment by NothinRandom** [comment]
OK, so 'len' is most likely the issue here: https://github.com/amzn/zeek-plugin-bacnet/blob/bf46f27f8f36a8cd73c1910e1566e50df30bcc6a/scripts/main.zeek#L150.  We'll probably want to check to see if 'len' is ever 3, 5, 6, 7 and not perform this, or implement byte shift to cover all cases within 8 bytes.

**Comment by humantargetjoe** [comment]
I'm also seeing this. Is there an intent to handle an invalid length in this case?  Or rely on a fix in the Zeek source?  Is there an issue open for against that?

**Comment by humantargetjoe** [comment]
@NothinRandom OK, thanks.  I wasn't sure what the resolution ended up being since the issue was closed and I'm seeing the same behavior when I pull master today.  The plugin is great.

**Comment by NothinRandom** [comment]
Hmm.  That is strange if you pulled latest yesterday and still experienced same issue.  I ran it against two pcaps that had this issue before and was resolved after update.  Any chance you could share pcap if it doesn't contain any confidential data?  Could DM me also.

**Comment by voteblake** [comment]
Reopening for now. I did a quick pass through our calls to `bytestring_to_count` and don't see the exact pattern of calling it with a variable length input but we do use it a lot with some offset math that could be hitting another odd-length value.

@humantargetjoe we might not need a PCAP (although it would still be helpful) if you can just share the whole log message you get with the error. For example, the error we originally noticed below indicates line 153 was the source of our problem. The error/line number from your issue would help us find if this needs to be addressed somewhere else in the code.

`1218932832.035836 error in /opt/bro/lib/zeek/plugins/packages/zeek-bacnet/scripts/./main.zeek, line 153: unsupported byte length for bytestring_to_count (bytestring_to_count(Bacnet::rest_of_data[(coerce Bacnet::rest_of_data_index to int), (coerce Bacnet::rest_of_data_index + Bacnet::len to int)], F))`

**Comment by humantargetjoe** [comment]
Sorry about the delay.  I'm trying to get approval to share one of the PCAPs.  In the interim, this is what I'm getting:

`zeek_pcap_1`  | 1552913969.601684 error in /usr/local/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek, line 160: unsupported byte length for bytestring_to_count (bytestring_to_count(Bacnet::rest_of_data[(coerce Bacnet::rest_of_data_index to int)], F))
`

I'm running through a docker container, and can provide that if it'll help, though the image itself is pretty bog-standard.

**Comment by voteblake** [comment]
Thanks @humantargetjoe - that's enough for us to get started, we're taking a look.

**Comment by NothinRandom** [comment]
@humantargetjoe so we've looked at both dpd.log and reporter.log, and nothing shows up.  We did see entries of this issue before the bytes_to_count function was implemented from a few days ago, but nothing new has shown up afterwards.  We'll continue to monitor these logs, but I think the best thing is to grab the pcap from you.  Even if you could export that one entry's data section as hex and ascii would be a great start for us to analyze.

**Comment by NothinRandom** [comment]
@humantargetjoe could you email me using my username at gmail?  I'll take a look.  Thanks

**Comment by Mohan-Dhawan** [comment]
I get similar errors for the following pcaps:
a) https://github.com/ITI/ICS-pcap/blob/master/TRIDIUM/plugfest-tridium-1/plugfest-tridium-1.pcap
b) https://github.com/ITI/ICS-pcap/blob/master/TRIDIUM/plugfest-tridium-2/plugfest-tridium-2.pcap

**Comment by NothinRandom** [comment]
@Mohan-Dhawan Issue here was that we handle the enumeration correctly.  It was addressed via [latest update](https://github.com/amzn/zeek-plugin-bacnet/commit/16b2b5358220477671c786feda542bd019f7509a#diff-e971e4317e8e746322cff8d24b0eff78R122)
