### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by Cyb3r4rch3r** [amzn/zeek-plugin-bacnet#28]
Hi all,

When loading this plugin installed via zkg on source built Zeek, I get the following error when deploying via zeekctl
`Duplicate &default attribute is ambiguous`

The full output displays this on multiple lines of the plugin
`error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 23: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 41: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 53: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 88: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 104: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 115: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 169: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 543: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 550: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 556: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 562: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 570: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 581: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 607: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 619: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 762: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 776: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 792: Duplicate &default attribute is ambiguous
error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 1894: Duplicate &default attribute is ambiguous`

Any idea why this may be, or what I can do to get this to work properly?

EDIT - I'm actually seeing this on all of the plugins installed from the amzn repos

**Comment by voteblake** [comment]
Fixed by #29 and am working on merging for the rest of the repo's today.
