### ISSUE TITLE
Add Vendor to Output

### ISSUE THREAD

**Issue by humantargetjoe** [amzn/zeek-plugin-bacnet#4]
It would be useful to have the Vendor for a device included in the output, especially for networks with a diverse number of devices to help sort inter-device communication downstream.

**Comment by NothinRandom** [comment]
@humantargetjoe so vendor info has been added for the "I Am" command.  However, I believe it also exists in the Read Property.  Investigating this to verify.  Would also help if you have PCAP to share.  Please follow same procedure like last time.

**Comment by NothinRandom** [comment]
Closing as vendor info has been added.  Please reopen if needed
