### ISSUE TITLE
Identifier or enumerator value in enumerated type definition already exists

### ISSUE THREAD

**Issue by hxnoyd** [amzn/zeek-plugin-bacnet#5]
Hi. I'm running Zeek in a Debian container that parses pcap files.

After installing the bacnet plugin the follow error messages occur when a pcap is parsed:
```
error in /usr/local/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./main.zeek, line 12: identifier or enumerator value in enumerated type definition already exists
error in /usr/local/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek, line 28: already defined (Bacnet::log_bacnet)
error in /usr/local/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek, line 36 and /usr/local/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./main.zeek, line 37: already defined (Bacnet::ports)
error in /usr/local/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek, line 46: already defined (Bacnet::bytes_to_count)
fatal error in error: BroType::AsFuncType (error/func) (error)
```

Any hints why this might be happening?
Thanks in advance.

**Comment by voteblake** [comment]
I haven't seen this error myself before, but it looks like its finding the plugin in two different locations that it is loading when starting up. It sees the script in both `/usr/local/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek` and `/usr/local/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./main.zeek`. This definitely shouldn't happen by default.

How did you install the plugin in your container? It might help if you could share your `Dockerfile` for the container and potentially the `local.bro`.

**Comment by hxnoyd** [comment]
@voteblake thanks for the hint! I was installing the plugin with non-root user, which caused the package duplication. I've moved the user change further down in the docker file, and now zeek is parsing the bacnet protocol like a charm.
 Thanks!

**Comment by voteblake** [comment]
Great, good to hear! Let us know if you notice any other issues as you start using it.
