### ISSUE TITLE
the URLs in README.md don't work when the README is on packages.zeek.org/packages/view

### ISSUE THREAD

**Issue by duffy-corelight** [amzn/zeek-plugin-bacnet#7]
See the four hyperlinks under Sharing and Contributing on
https://packages.zeek.org/packages/view/0f30b402-f435-11e9-9321-0a645a3f3086
are all dead links.

**Comment by voteblake** [comment]
Thanks @duffy-corelight - looks like we just need to change the links in the README from relative to absolute links to the GitHub. This should make sure that when the Markdown is rendered at the Zeek package repository they still point to the correct docs.

**Comment by duffy-corelight** [comment]
Yeah, that was my assessment as well. As I dig-in on updating
zeek-plugin-bacnet, I'll make that one of my pull-requests.

Were you the original author, or have access to him/her? I'd love to ask a
few questions about what was chosen to include into bacnet.log, and what is
omitted.
      - Duffy

**Comment by voteblake** [comment]
That's awesome if you'd like to put together a pull request, I'd appreciate it. I helped out but @NothinRandom did most of the heavy lifting. We're both still the maintainers so definitely reach out. If you have questions or ideas for improvement you want to discuss you can open an issue on the repository and we both get notified.

If there's data we're not logging that you think is interesting we're 100% open to adding it if technically feasible.

**Comment by NothinRandom** [comment]
@duffy-corelight, I'll make a note of this and update in the next commit.

**Comment by NothinRandom** [comment]
@duffy-corelight, this has been addressed with latest commit.  I'll let you close if you see that it meets satisfaction.  Thank you very much for your help in improving this plugin!

**Comment by duffy-corelight** [comment]
Success! tested from https://packages.zeek.org/tags
