### ISSUE TITLE
BACnet with that capitalization is industry standard

### ISSUE THREAD

**Issue by duffy-corelight** [amzn/zeek-plugin-bacnet#9]
I see in the output from
```
/usr/local/zeek/bin/zeek -N | grep -i net
Zeek::Login - Telnet/Rsh/Rlogin analyzers (built-in)
Zeek::NetBIOS - NetBIOS analyzer support (built-in)
Zeek::BACNET - Bacnet Protocol analyzer (dynamic, no version information)
```
that the module name is ALL-CAPS, and the description is Initial-Cap, but BACnet with precisely that capitalization, is the only usage which is industry standard.

**Comment by NothinRandom** [comment]
@duffy-corelight, thanks for the info!  I'm going to correct all/most of the open issues and push them at the next commit.  Keep them coming, and we'll try to keep up with you :)

Just to confirm, we should change `Zeek::BACNET - Bacnet Protocol analyzer (dynamic, no version information)` to `Zeek::BACnet - BACnet Protocol analyzer (dynamic, no version information)`

**Comment by duffy-corelight** [comment]
That capitalization change you show above is what I would recommend. Where it doesn't break anything, I would further encourage as much source code and string value changeover as possible. Only zeek-plugin-bacnet would remain all-lowercase, and only ANALYZER_BACNET would be ALL_CAPS. 

The line `plugin::Configuration Plugin::Configure() {
    AddComponent(new ::analyzer::Component("BACNET",
::analyzer::bacnet::BACNET_Analyzer::Instantiate));`
in src/Plugin.cc just above where you'll be changing:
```
    config.name = "Zeek::BACNET";
    config.description = "Bacnet Protocol analyzer";
```
when resolving this issue, about broke my heart seeing so many variations all in a row.

Over in https://lists.zeek.org/archives/list/zeek-dev@lists.zeek.org/thread/C7IDSZKV7DAAMZGUL63QM4R7JWW7F6BL/ we're having a discussion of the universal capitalization and punctuation conventions for Zeek packages. For example zeek -NN | grep -i net
output below shows existing variation, and where this package is the outlier, it should try to become regularized and conformant.
```
    [Event] irc_network_info
Zeek::Login - Telnet/Rsh/Rlogin analyzers (built-in)
    [Analyzer] Telnet (ANALYZER_TELNET, enabled)
Zeek::NetBIOS - NetBIOS analyzer support (built-in)
    [Analyzer] Contents_NetbiosSSN (enabled)
    [Analyzer] NetbiosSSN (ANALYZER_NETBIOSSSN, enabled)
    [Event] netbios_session_message
    [Event] netbios_session_request
    [Event] netbios_session_accepted
    [Event] netbios_session_rejected
    [Event] netbios_session_raw_message
    [Event] netbios_session_ret_arg_resp
    [Event] netbios_session_keepalive
    [Function] decode_netbios_name
    [Function] decode_netbios_name_type
    [Event] rdp_client_network_data
Zeek::BACNET - Bacnet Protocol analyzer (dynamic, no version information)
    [Analyzer] BACNET (ANALYZER_BACNET, enabled)
    [Event] bacnet
```

**Comment by NothinRandom** [comment]
Yeah, I agree.  I think a bunch of things were converted during the great migration from bro 2.6.x to zeek 3.x.  Regardless, this will be updated.

**Comment by NothinRandom** [comment]
@duffy-corelight, latest commit addresses this issue in naming convention.  I'll let you close it if you see that it meets standard

**Comment by duffy-corelight** [comment]
Great and thorough changeover. Thanks!
